server:
  error:
    include-stacktrace: never

spring:
  application:
    name: pokedex
  datasource:
    url: jdbc:mysql://localhost:3306/pokedex-api?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: 755dd7f2-3c7b-4541-939b-12aeda7b27df
